void *malloc_checked(unsigned int b);
int _putchar(char c);
char *string_nconcat(char *s1, char *s2, unsigned int n);
void *_calloc(unsigned int nmemb, unsigned int size);
int *array_range(int min, int max);
void *_realloc(void *ptr, unsigned int old_size, unsigned int new_size);
int onlyNumbers(char *c);
int _strlen(char *s);
void multiply(char *f, char *s);
char *_memset(char *s, char b, unsigned int n);
